### ISSUE TITLE
Win32 v3.2.2, Alt-X does nothing if the file being edited has been changed but not saved

### ISSUE THREAD

**Issue by dlrourke** [adamyg/grief#16]
First, thank you for both Grief and the Windows version of Midnight Commander!

Using the Win32 version 3.2.2 of Grief, if the file has been changed, but not saved with Alt-W, nothing happens if Alt-X is entered.  Furthermore, F10 followed by exit doesn't work either (but abort does).

Is this the behavior you intended?  I would have thought a message such as "File changed but not saved; reply W (save then exit), X (exit), Enter (continue Grief session)." would be appropriate.

**Comment by adamyg** [comment]
shall review, thx

**Comment by adamyg** [comment]
3.2.2-build23
