### ISSUE TITLE
Files are corrupted when restore / backup has invalid paths

### ISSUE THREAD

**Issue by milnak** [adamyg/grief#38]
On a win32 system without a K: drive, add the following to `$env:AppData/.grief/_grinit`.

```text
restore: save=full cache=k:/devl/.restore savehist=yes scrapper=yes
backup: dir=k:/devl/.backup version=9
```

now edit and save an existing file then reopen it in grief.  The first two lines (maybe more) will be corrupted.

**Comment by adamyg** [comment]
Direct copy of _grinit.example, which is intended as an example only; yet backup macro should verify paths.
