### ISSUE TITLE
 Two Alt+a copy and/or paste errors

### ISSUE THREAD

**Issue by adamyg** [adamyg/grief#41]
Reference: https://sourceforge.net/p/grief/tickets/36/

````
1 | Use Alt+a and mark a fragment of text in a line.
| keypad +
| move the cursor to elsewhere in the buffer.
| keypad ins
? the last marked and copied character is erroneously missing.
? a blank line is erroneously inserted.

2 | With the cursor at the beginning of a line.
| use Alt+a and down arrow to mark one or more lines of text.
| keypad -
? the first character of a following, UNMARKED line, is erroneously deleted.
| move the cursor to elsewhere in the buffer.
| keypad +
? an extra blank line is erroneously inserted.
````

ALT+A = MK_NONINC, which shall include any trailing new-line from the previous if the cursor is positioned at col=1, whereas ALT+L = MK_LINE, behavior is line aware.

Changing MK_NONINC semantics is not practical; new mode would be needed or replacement macro required which behaves like MK_NONINC2 (aka back2 if col=1)

**Comment by raygwinn** [comment]
What does all that mean in English.

**Comment by adamyg** [comment]
ALT+A = is mapped to mark(MK_NONINC=4); see "<F10>explain mark" and "<Alt-H>Keyboard Summary".
Changing the semantics of anchor type MK_NONINC is not practical, due to its side effects.
Would need a new anchor type (say MK_NONINC2) and have ALT+A key mapped explicitly within your local profile.

**Comment by raygwinn** [comment]
Perhaps you think I understand the internal workings of Grief, I do not.

Are you going to fix the problem or not?

Thank you for all the work you provide on Grief.

**Comment by adamyg** [comment]
Still considering options; ticket notes are part of this process.
