### ISSUE TITLE
Why is 'make release install' trying to copy a gr.exe in Linux?

### ISSUE THREAD

**Issue by denlun** [adamyg/grief#47]
Just ran a git clone on a PopOS (Ubuntu derivative) and ran:
```
./configure_new
make release
sudo make release install
```
and  is failing with:
`/usr/bin/install -c -m 0755 /home/user/grief/bin.gcc/release/gr.exe /usr/local/bin
/usr/bin/install: cannot stat '/home/user/grief/bin.gcc/release/gr.exe': No such file or directory`

I did have to add a few more packages than just build-essential but didn't have any other issues.

**Comment by adamyg** [comment]
fixed, build-25

**Comment by denlun** [comment]
Thanks! Works just fine in Pop!OS 22.04.
