### ISSUE TITLE
Status bar 'command field' font is always dark

### ISSUE THREAD

**Issue by denlun** [adamyg/grief#49]
Not really sure if this is actually a problem with the majority of the terminal programs...
Have tried several different terminals and when a dark theme is used you cannot read the command field. The main issue is that many terminals do not honor the system color theme (at least in Gnome).
Gnome Terminal has to have theme set to light in Preferences (or leave it default if the system theme is light).
Rxvt defaults to a light theme so no issues out of the box.
Terminator defaults to dark, can't read.
Terminology defaults to dark, can't read.
Alacritty defaults to dark, can't read.
Kitty defaults to dark, can't read.
Funnily enough Cool Retro Term gets it right even tho it defaults to dark... and with the amber default it looks pretty much like Brief did back in the day on my Ericsson PC...
And another thing I noticed while trying out the terminals is that in many of them Grief tended to put the horizontal scroll bar one third of the screen up and with some odd line lengths, this corrected itself when resizing the window.

**Comment by adamyg** [comment]
"And another thing I noticed while trying out the terminals is that in many of them Grief tended to put the horizontal scroll bar one third of the screen up and with some odd line lengths, this corrected itself when resizing the window." 
.. screen captures, thanks

**Comment by adamyg** [comment]
Under WIN32:, 16-colorscheme's being incorrectly mapped on a 256 color display.

**Comment by denlun** [comment]
Here is Terminator where Grief has been started without resizing the window.
![terminator-grief](https://github.com/adamyg/grief/assets/9013120/6a86be83-d8bc-4088-8d97-48cefe6a1c0d)

Note the lines with a '+' in the vertical scroll and also the horizontal scroll.
As soon as your resize the window it's corrected.

**Comment by adamyg** [comment]
Not familiar with, https://terminator-gtk3.readthedocs.io/en/latest/, what is the TERM setting in use?
Wondering what are the supported control-escapes, including "Device Attributes" report.
Run grief with -d enabled and forward the opening section log detailing the terminal.

**Comment by adamyg** [comment]
unconditionally

**Comment by denlun** [comment]
I verified the > 80 using GNOME Terminal since it happens there as well and seems if you set the startup width to 81 or greater the problem doesn't occur.
The TERM in GNOME Terminal and Terminator is the same: xterm-256color
[grief.log](https://github.com/adamyg/grief/files/15419453/grief.log)
