### ISSUE TITLE
Can't see certain messages

### ISSUE THREAD

**Issue by blakemcbride** [adamyg/grief#68]
build-27 fixed the problem I was having building on my Fedora Linux box.  Thank you.

However, I noticed the following problem.  If I do the following:

```
$ gr
abcde
alt-X
```

I get a blank message at the bottom of the screen.  I assume it's asking me something has changed; do I really want to quit?  But instead it just displays about 60 spaces.  I presume it's a text color or font issue.

Thanks!

**Comment by adamyg** [comment]
Terminal/font/color-depth setup?  Attempt an alternative colorscheme, examples include
 ``gr --colorscheme=zernburn``,  ``gr --lite`` and  ``gr --dark``.  See macro/colors for other bundled schemes.

**Comment by blakemcbride** [comment]
My preference is no colors at all anywhere.  No language colorization, etc.  How can I set that?  Thanks!

**Comment by adamyg** [comment]
```gr --nocolor```

**Comment by blakemcbride** [comment]
Thanks.  That fixed the blank message issue too.

I suppose I'll create a shell script to that when I run gr it always adds the --nocolor option.

Thanks!

**Comment by blakemcbride** [comment]
Is there anyway of putting (effectively) `--nocolor` in a config file?

**Comment by adamyg** [comment]
export GRFLAGS=--nocolor

**Comment by adamyg** [comment]
#73

**Comment by blakemcbride** [comment]
Perfect.  Thanks!
