### ISSUE TITLE
INSTALL.md issues

### ISSUE THREAD

**Issue by blakemcbride** [adamyg/grief#69]
On build-27 of INSTALL.md I am seeing:

```
[...]
?configure --prefix=/home/user/grief?
[...]
?make release?              - build software.
[...]
     ?sudo make release install? - install for common/system usage; or                                                                        │
│   or ?make release install?      - local installation.   
```

What are all of the question marks?

**Comment by adamyg** [comment]
Context please, for example [INSTALL.md](https://github.com/adamyg/grief/blob/master/INSTALL.md). Tested several environments, no visible issues. If a suitable utf8 terminal font is generally required, terminal/font is use?

Run ```<F10>ascii``` and generate a ```Unicode Hex Chart``` to preview; note display wont be 100% dependent on the active font.

**Comment by blakemcbride** [comment]
I am using a stock Fedora installation.  I've not messed with the fonts or colors.

**Comment by blakemcbride** [comment]
Looks fine now.  Must be my mistake.  Thanks and sorry.
