### ISSUE TITLE
Latest release being rejected by Windows Defender as containing a virus

### ISSUE THREAD

**Issue by georgezengin** [adamyg/grief#75]
![image](https://github.com/adamyg/grief/assets/43248841/fcb115f7-b092-4414-b461-59d52f38f25e)

**Comment by adamyg** [comment]
Believe false positive: see https://sourceforge.net/p/grief/tickets/39/

**Comment by adamyg** [comment]
Still seeing false positives; removed grwc from package; shall again review at later date.
